// This file is generated by icon spritesheet generator

export const iconNames = [
	'lucide--x',
	'lucide--circle',
	'lucide--chevron-right',
	'lucide--check',
] as const

export type IconName = (typeof iconNames)[number]
